name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build:all

      - name: Publish to Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
